### ISSUE TITLE
Bug report: Crystals on HCsCR are slower than headbopping

### ISSUE THREAD

**Issue by realFusionFusion** [FemboyPvE/HCsCR#7]
**How to reproduce:**
1. Turn off the mod, headbop and figure out the timing you need for your left and right clicks
2. Turn on the mod, crystal and use the same timing as when you were headbopping
3. Notice how sometimes your crystals don't even place 

You'd have to time your clicks slower to crystal properly.

**Comment by VidTu** [comment]
I don't care.
